/**
 * The shared fixture that holds the Python delivery grade to the viewer grade.
 *
 * A Deliver master is graded in Python (color/grading.py apply_grading, fed by
 * viewer_grade_kwargs from the payload the viewer sends). The picture on screen
 * is graded by the shader, which grade_render.test.mjs holds to gradePixelFull
 * in js/radiance_grade.js. This file builds a set of grade payloads and pixels,
 * grades them with gradePixelFull, and writes the result to
 * tests/fixtures/viewer_grade_parity.json, which
 * tests/test_viewer_grade_parity.py feeds through the Python grade.
 *
 * viewer_grade_fixture.test.mjs regenerates the fixture and compares it with the
 * committed file, so neither side can change without the other noticing.
 *
 * Regenerate: node js/tests/viewer_grade_fixture.mjs --write
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { gradePixelFull } from '../radiance_grade.js';

export const FIXTURE_PATH = join(dirname(fileURLToPath(import.meta.url)), '..', '..', 'tests', 'fixtures', 'viewer_grade_parity.json');

/** A curve table as the editor emits it: 256 RGBA entries, float32 values. */
function curveTable(fr, fg, fb) {
    const t = new Float32Array(1024);
    for (let i = 0; i < 256; i++) {
        const x = i / 255;
        t.set([fr(x), fg(x), fb(x), 1], i * 4);
    }
    return Array.from(t);
}

function hueTable() {
    const t = new Float32Array(1024);
    for (let i = 0; i < 256; i++) {
        const h = i / 255;
        t.set([0.5 + 0.05 * Math.sin(2 * Math.PI * h), 0.5 + 0.1 * Math.cos(2 * Math.PI * h), 0.5, 1], i * 4);
    }
    return Array.from(t);
}

const PIXELS = [
    [0, 0, 0], [0.18, 0.18, 0.18], [0.6, 0.5, 0.4], [0.9, 0.2, 0.05], [0.02, 0.05, 0.1],
    [1.0, 1.0, 1.0], [2.5, 1.2, 0.4], [-0.05, 0.2, 0.3], [0.35, 0.7, 0.95], [0.001, 0.003, 0.0005],
];

/**
 * Payloads use the delivery keys (the ones js/radiance_viewer.js sends to
 * /radiance/deliver), so the Python side is exercised through the same mapping
 * a real Deliver uses.
 */
const CASES = [
    { name: 'neutral', grading: {} },
    { name: 'contrast about 18% grey', grading: { contrast: 1.6 } },
    { name: 'contrast, moved pivot', grading: { contrast: 0.7, pivot: 0.4 } },
    { name: 'old grade without a pivot', grading: { contrast: 1.3, saturation: 1.1 } },
    { name: 'white balance', grading: { temperature: 0.6, tint: -0.3 } },
    { name: 'primaries', grading: {
        exposure: 0.5, offset: [0.01, 0, -0.01], lift: [0.03, 0, -0.02], gain: [1.1, 1, 0.9],
        gamma: [1.2, 1, 0.85], contrast: 1.25, pivot: 0.18, saturation: 1.3 } },
    { name: 'luma mix after the primaries', grading: { exposure: 1, gain: [1.2, 1.2, 1.2], saturation: 1.8, hue_shift: 25, lumaMix: 0 } },
    { name: 'tone and colour', grading: {
        shadows: 0.4, highlights: -0.3, colorBoost: 0.3, hue_shift: -15,
        logShadow: [0.05, 0, -0.02], logMidtone: [0, 0.04, 0], logHighlight: [-0.03, 0, 0.05],
        printerR: 6, printerG: -2, printerB: 3 } },
    { name: 'curves and hue curves', grading: {
        curveTable: curveTable((x) => Math.pow(x, 0.8), (x) => x, (x) => Math.min(1, 1.1 * x)), curveMix: 1,
        secondaryCurveTable: hueTable(), secondaryCurveMix: 1, saturation: 0.9 } },
    { name: 'ACEScct, Rec.709 source', grading: {
        colorScience: 1, offset: [0.02, 0, -0.01], gain: [1.05, 1, 0.95], gamma: [1.1, 1, 1], exposure: 0.3 } },
    { name: 'ACEScct, ACEScg source', grading: { colorScience: 1, gain: [1.1, 1, 0.9], sourceGamut: 1 } },
    { name: 'ACEScct, ACES2065-1 source', grading: { colorScience: 1, lift: [0.01, 0, 0], sourceGamut: 2 } },
    { name: 'everything', grading: {
        exposure: -0.4, temperature: -0.5, tint: 0.2, offset: [0.005, 0, 0], lift: [0.02, 0.01, 0],
        gain: [1.05, 0.98, 1.02], gamma: [0.9, 1.1, 1], contrast: 1.4, pivot: 0.2, saturation: 1.2,
        shadows: -0.2, highlights: 0.25, colorBoost: 0.2, hue_shift: 40, lumaMix: 0.3,
        logShadow: [0, 0.03, 0], printerR: -4, printerB: 5,
        curveTable: curveTable((x) => x * x * (3 - 2 * x), (x) => x, (x) => x), curveMix: 0.8 } },
];

/** The delivery payload, in the field names gradePixelFull reads. */
function toState(g) {
    const { hue_shift, sourceGamut, ...rest } = g;
    return { ...rest, ...(hue_shift !== undefined ? { hueShift: hue_shift } : {}) };
}

export function buildFixture() {
    return {
        note: 'Generated by js/tests/viewer_grade_fixture.mjs from js/radiance_grade.js gradePixelFull. Do not edit.',
        pixels: PIXELS,
        cases: CASES.map(({ name, grading }) => ({
            name,
            grading,
            expected: PIXELS.map((px) => gradePixelFull(px, toState(grading), { gamut: grading.sourceGamut ?? 0 })),
        })),
    };
}

if (process.argv.includes('--write')) {
    writeFileSync(FIXTURE_PATH, JSON.stringify(buildFixture()) + '\n');
    console.log(`wrote ${FIXTURE_PATH}`);
}
